server:
  port: 8080

spring:
  profiles:
    include: secret
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  second-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${HISTORY_DB_URL}
    username: ${HISTORY_DB_USERNAME}
    password: ${HISTORY_DB_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    defer-datasource-initialization: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

#  sql:
#    init:
#      mode: always

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    info:
      root: debug
    com.ssafy.seoulpop: DEBUG